language: cpp
compiler:
  - gcc
install: 
  - sudo wget http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.bz2/download -O /usr/include/boost_1_55_0.tar.bz2
  - sudo tar --bzip2 -xf /usr/include/boost_1_55_0.tar.bz2 -C /usr/include
  #Decomentar las siguientes lineas y comentar la ultima para compilar absolutamente todo  
  #- sudo apt-get install doxygen
#script: make && ./bin/test
script: make test && ./bin/test
